const actionTypes = Object.freeze({
  //app
  APP_START_UP_COMPLETE: "APP_START_UP_COMPLETE",
  SET_CONTENT_OF_CONFIRM_MODAL: "SET_CONTENT_OF_CONFIRM_MODAL",
  CHANGE_LANGUAGE: "CHANGE_LANGUAGE",

  //user
  ADD_USER_SUCCESS: "ADD_USER_SUCCESS",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAIL: "USER_LOGIN_FAIL",
  PROCESS_LOGOUT: "PROCESS_LOGOUT",
  //cus
  GET_A_USER_BY_ID_SUCCESS: "GET_A_USER_BY_ID_SUCCESS",
  GET_A_USER_BY_ID_FAIL: "GET_A_USER_BY_ID_FAIL",

  EDIT_USER_SUCCESS: "EDIT_USER_SUCCESS",
  EDIT_USER_FAILED: "EDIT_USER_FAILED",
  //product
  CREATE_PRODUCT_SUCCESS: "CREATE_PRODUCT_SUCCESS",
  CREATE_PRODUCT_FAIL: "CREATE_PRODUCT_FAIL",

  GET_ALL_PRODUCTS_SUCCESS: "GET_ALL_PRODUCTS_SUCCESS",
  GET_ALL_PRODUCTS_FAIL: "GET_ALL_PRODUCTS_FAIL",

  GET_PRODUCTS_SEARCH_SUCCESS: "GET_PRODUCTS_SEARCH_SUCCESS",
  GET_PRODUCTS_SEARCH_FAIL: "GET_PRODUCTS_SEARCH_FAIL",

  DELETE_PRODUCT_SUCCESS: "DELETE_PRODUCT_SUCCESS",
  DELETE_PRODUCT_FAIL: "DELETE_PRODUCT_FAIL",

  UPDATE_PRODUCT_SUCCESS: "UPDATE_PRODUCT_SUCCESS",
  UPDATE_PRODUCT_FAIL: "UPDATE_PRODUCT_FAIL",

  ADD_PRODUCT_CART: "ADD_PRODUCT_CART",
  ADD_PRODUCT_CART_FAIL: "ADD_PRODUCT_CART_FAIL",

  DELETE_PRODUCT_CART: "DELETE_PRODUCT_CART",
  DELETE_PRODUCT_CART_FAIL: "DELETE_PRODUCT_CART_FAIL",

  GET_CART_BY_USER: "GET_CART_BY_USER",
  GET_CART_BY_USER_FAIL: "GET_CART_BY_USER_FAIL",

  UPDATE_CART_SUCCESS: "UPDATE_CART_SUCCESS",
  UPDATE_CART_FAIL: "UPDATE_CART_FAIL",

  GET_PRODUCTS_BYTYPE_SUCCESS: "GET_PRODUCTS_BYTYPE_SUCCESS",
  GET_PRODUCTS_BYTYPE_FAIL: "GET_PRODUCTS_BYTYPE_FAIL",

  GET_PRODUCTS_BY_BRAND_SUCCESS: "GET_PRODUCTS_BY_BRAND_SUCCESS",
  GET_PRODUCTS_BY_BRAND_FAIL: "GET_PRODUCTS_BY_BRAND_FAIL",

  GET_PRODUCTS_NEW_SUCCESS: "GET_PRODUCTS_NEW_SUCCESS",
  GET_PRODUCTS_NEW_FAIL: "GET_PRODUCTS_NEW_FAIL",

  GET_PRODUCTS_BOUGHT_SUCCESS: "GET_PRODUCTS_BOUGHT_SUCCESS",
  GET_PRODUCTS_BOUGHT_FAIL: "GET_PRODUCTS_BOUGHT_FAIL",

  GET_PRODUCTS_HOT_SUCCESS: "GET_PRODUCTS_HOT_SUCCESS",
  GET_PRODUCTS_HOT_FAIL: "GET_PRODUCTS_HOT_FAIL",

  GET_PRODUCTS_PRIME_SUCCESS: "GET_PRODUCTS_PRIME_SUCCESS",
  GET_PRODUCTS_PRIME_FAIL: "GET_PRODUCTS_PRIME_FAIL",

  GET_PRODUCTS_PERCENT_SUCCESS: "GET_PRODUCTS_PERCENT_SUCCESS",
  GET_PRODUCTS_PERCENT_FAIL: "GET_PRODUCTS_PERCENT_FAIL",
  //order
  CREATE_ORDER_SUCCESS: "CREATE_ORDER_SUCCESS",
  CREATE_ORDER_FAIL: "CREATE_ORDER_FAIL",

  GET_CART_BY_ID_SUCCESS: "GET_CART_BY_ID_SUCCESS",
  GET_CART_BY_ID_FAIL: "GET_CART_BY_ID_FAIL",

  GET_CART_BY_USERID_SUCCESS: "GET_CART_BY_USERID_SUCCESS",
  GET_CART_BY_USERID_FAIL: "GET_CART_BY_USERID_FAIL",

  //orderadmin
  GET_CHECKING_ORDER_SUCCESS: "GET_CHECKING_ORDER_SUCCESS",
  GET_CHECKING_ORDER_FAIL: "GET_CHECKING_ORDER_FAIL",

  GET_ORDER_BY_STATUS_SUCCESS: "GET_ORDER_BY_STATUS_SUCCESS",
  GET_ORDER_BY_STATUS_FAIL: "GET_ORDER_BY_STATUS_FAIL",

  DELETE_ORDER_SUCCESS: "DELETE_ORDER_SUCCESS",
  DELETE_ORDER_FAIL: "DELETE_ORDER_FAIL",

  UPDATE_ORDER_STATUS_SUCCESS: "UPDATE_ORDER_STATUS_SUCCESS",
  UPDATE_ORDER_STATUS_FAIL: "UPDATE_ORDER_STATUS_FAIL",

  //admin
  GET_ALL_CUS_SUCCESS: "GET_ALL_CUS_SUCCESS",
  GET_ALL_CUS_FAIL: "GET_ALL_CUS_FAIL",

  GET_ALL_ADMIN_SUCCESS: "GET_ALL_ADMIN_SUCCESS",
  GET_ALL_ADMIN_FAIL: "GET_ALL_ADMIN_FAIL",

  UPDATE_CUS_EXTRA_SUCCESS: "UPDATE_CUS_EXTRA_SUCCESS",
  UPDATE_CUS_EXTRA_FAIL: "UPDATE_CUS_EXTRA_FAIL",

  //statistic
  GET_TOP_SOLD_PRODUCTS_SUCCESS: "GET_TOP_SOLD_PRODUCTS_SUCCESS",
  GET_TOP_SOLD_PRODUCTS_FAIL: "GET_TOP_SOLD_PRODUCTS_FAIL",

  GET_TOP_STOCK_PRODUCTS_SUCCESS: "GET_TOP_STOCK_PRODUCTS_SUCCESS",
  GET_TOP_STOCK_PRODUCTS_FAIL: "GET_TOP_STOCK_PRODUCTS_FAIL",

  GET_TOP_SOLDFEW_PRODUCTS_SUCCESS: "GET_TOP_SOLDFEW_PRODUCTS_SUCCESS",
  GET_TOP_SOLDFEW_PRODUCTS_FAIL: "GET_TOP_SOLDFEW_PRODUCTS_FAIL",

  GET_TOP_ORDER_MONEY_SUCCESS: "GET_TOP_ORDER_MONEY_SUCCESS",
  GET_TOP_ORDER_MONEY_FAIL: "GET_TOP_ORDER_MONEY_FAIL",

  GET_ORDER_MONTH_SUCCESS: "GET_ORDER_MONTH_SUCCESS",
  GET_ORDER_MONTH_FAIL: "GET_ORDER_MONTH_FAIL",
});

export default actionTypes;
